version: '3.8'
services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 chaigrill.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=production-secure-key-chai-grill-kochi
      - ALLOWED_HOSTS=*
