# Generated by Django 5.2.6 on 2026-08-14 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('icon_class', models.CharField(default='fa-fire', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Menu Categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Padamughal, Kakkanad', max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('area', models.CharField(help_text='e.g., Kakkanad, Kochi', max_length=100)),
                ('phone', models.CharField(help_text='e.g., 9747478292', max_length=20)),
                ('whatsapp_number', models.CharField(help_text='e.g., 919747478292', max_length=20)),
                ('opening_time', models.CharField(default='4:00 PM – 2:00 AM', max_length=50)),
                ('google_maps_url', models.URLField(blank=True, null=True)),
                ('order_priority', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Outlet / Branch',
                'verbose_name_plural': 'Outlets / Branches',
                'ordering': ['order_priority'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('is_veg', models.BooleanField(default=False)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_chef_special', models.BooleanField(default=False)),
                ('spice_level', models.PositiveSmallIntegerField(choices=[(0, 'Mild'), (1, 'Medium'), (2, 'Spicy'), (3, 'Extra Fiery')], default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.menucategory')),
            ],
            options={
                'ordering': ['-is_bestseller', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReservationInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('inquiry_type', models.CharField(choices=[('table', 'Table Reservation'), ('catering', 'Party / Event Catering'), ('general', 'General Enquiry')], default='table', max_length=20)),
                ('booking_time', models.DateTimeField()),
                ('guests_count', models.PositiveIntegerField(default=2)),
                ('special_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('contacted', 'Customer Contacted'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='core.outlet')),
            ],
            options={
                'verbose_name': 'Reservation / Inquiry',
                'verbose_name_plural': 'Reservations & Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
