# Generated by Django 5.2.6 on 2026-08-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Best Bucket, Jolley Meal, Family Combo', max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('target_audience', models.CharField(blank=True, help_text='e.g. For 4-6 Legends / Hungry Family', max_length=120)),
                ('includes', models.TextField(help_text='Bullet points separated by commas: 1 Full Shawaya, 10PS Don Chilly, Fries L, 2L Cola, Mayo')),
                ('badge', models.CharField(blank=True, default='POPULAR COMBO', max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('order_priority', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Combo / Bucket Deal',
                'verbose_name_plural': 'Combos & Bucket Deals',
                'ordering': ['order_priority'],
            },
        ),
        migrations.RemoveField(
            model_name='reservationinquiry',
            name='inquiry_type',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='portion_info',
            field=models.CharField(blank=True, help_text='e.g. 4PS / 8PS, Full / Half / Qtr, + Fries & Mayo', max_length=120),
        ),
        migrations.AddField(
            model_name='outlet',
            name='email',
            field=models.EmailField(default='chaisgrills@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='outlet',
            name='image_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='icon_class',
            field=models.CharField(default='fa-fire', help_text='FontAwesome icon class', max_length=50),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='area',
            field=models.CharField(help_text='e.g. Big Building, 30-19/C16, Thoppumpady', max_length=120),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='name',
            field=models.CharField(help_text='e.g. Thoppumpady, Kochi', max_length=150),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='phone',
            field=models.CharField(help_text='e.g. 8943777001', max_length=20),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='whatsapp_number',
            field=models.CharField(help_text='e.g. 918943777001', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservationinquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
