# Generated by Django 5.2.6 on 2026-08-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_combomeal_remove_reservationinquiry_inquiry_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combomeal',
            name='includes',
            field=models.TextField(help_text='Items separated by commas'),
        ),
        migrations.AlterField(
            model_name='combomeal',
            name='target_audience',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
