# Generated by Django 6.1 on 2026-08-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_combomeal_includes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo directly from your device (recommended). Takes priority over the Image URL below.', null=True, upload_to='menu_items/%Y/%m/'),
        ),
    ]
