# Generated by Django 6.1 on 2026-08-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True, help_text='Only used if no image is uploaded above (e.g. an external/Unsplash link).', max_length=500),
        ),
    ]
