# Generated by Django 5.2.6 on 2026-08-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_menuitem_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Internal label, e.g. 'Cocktail Pour Reel'", max_length=150)),
                ('video', models.FileField(help_text='Upload an MP4 file (keep it short, under ~15MB for fast loading).', upload_to='promo_videos/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional poster image shown before the video plays.', null=True, upload_to='promo_videos/thumbs/%Y/%m/')),
                ('link_url', models.URLField(blank=True, help_text='Optional — where the widget takes users if they tap the expand icon.')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Floating Promo Video',
                'verbose_name_plural': 'Floating Promo Videos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
