# Generated by Django 5.2.6 on 2026-08-21 05:46

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_promovideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promovideo',
            name='video',
            field=models.FileField(help_text='Upload an MP4 file (keep it short, under ~15MB for fast loading).', storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='promo_videos/%Y/%m/'),
        ),
    ]
