# Generated by Django 5.2.6 on 2026-08-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_promovideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='promovideo',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('menu', 'Menu'), ('loaded combos', 'Loaded Combos')], default='home', max_length=20),
        ),
    ]
