# Generated by Django 5.2.6 on 2026-10-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_promovideo_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promovideo',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('menu', 'Menu'), ('combos', 'Loaded Combos')], default='home', max_length=20),
        ),
    ]
